In [ ]:
print("johnny johnny yes pappa")

johnny johnny yes pappa

In [ ]:

num1 = 10
num2 = 20
average = find_average(number1, number2)
print(f"The average is: {average}")

NameError: name 'find_average' is not defined

In [ ]:


number1 = float(input("Enter the first number: "))
number2 = float(input("Enter the second number: "))

average = find_average(number1, number2)
print(f"The average of {number1} and {number2} is: {average}")

In [ ]:

import math

def calculate_square_root(number):

    if number < 0:
        return "Cannot calculate square root of a negative number."
    else:
        return math.sqrt(number)


num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))


sqrt_num1 = calculate_square_root(num1)
sqrt_num2 = calculate_square_root(num2)
print(f"The square root of {num1} is: {sqrt_num1}")
print(f"The square root of {num2} is: {sqrt_num2}")

In [ ]:
word1="hello"
word2="world"
Result=word1+word2
print(Result)

In [ ]:
word1="helloworld"
print(len(word1))

In [ ]:
word1="helloworld"
print(len(word1))
print(word1[0])
print(word1[2])
print(word1[1])
print(word1)

In [ ]:
a="helloworld"
print(a[1:4])
print(len(a))

In [ ]:
a="helloworld"
print(a[-2])

In [ ]:
a="hello world"
print(a[0::8])

hr

In [ ]:

str="Helloworld"
len(str)
str.endswith("ld")
str.capitalize()
str.replace("hello","hh")
str.find("world")
str.count("o")

2

In [ ]:
str=" the usa use $ currency which is the leading currnecy in the world"
str.count("$")

1

In [ ]:
str=" the usa use $ currency which is the leading currnecy in the world"
str.find("$")

13

In [ ]:
text="hello"
reversed_text="".join(reversed(text))
print(reversed_text)

olleh

In [ ]:
digits=("1","2","3","4","5","6","7","8","9","0")
print(digits[1:10:2])

('2', '4', '6', '8', '0')

In [ ]:
s="microsoft copilot"
print(s[5:17:1])

soft copilot

In [ ]:
s="helloworld"
print(s[::-1])

dlrowolleh

In [ ]:
a=input("enter the color of signal::")
if a=="red":
  print("stop")
elif a=="green":
  print("go")
elif a=="yellow":
    print("ready")

enter the color of signal::red
stop

In [ ]:
str="i am punith"
len(str)

11

In [ ]:
str="i am punith"
str.endswith("t")

False

In [ ]:
str="i am punith"
str.replace("punith","punith aradhya p")

'i am punith aradhya p'

In [ ]:
s=[1,2,3,4,5]
print(len(s))

5

In [ ]:
s=["NIveedan","eee","eeeeeeeee"]
print(s[::-1])

['eeeeeeeee', 'eee', 'NIveedan']

In [ ]:
s=[1,2,5,7,9,12]
s.insert(2,3)
print(s)

[1, 2, 3, 5, 7, 9, 12]

In [ ]:
s=[3,5,8,7,6]
s.pop(2)
print(s)

[3, 5, 7, 6]

In [ ]:
#wap to sort the list
l=[55,6,233,7,2233,]
l.sort()
print(l)

[6, 7, 55, 233, 2233]

In [ ]:
#wap to delete the elemnt from the list
l=[3,4,1,44,222,66,33]
l.pop(1)
print(l)

[3, 1, 44, 222, 66, 33]

In [ ]:
#differnce btw pop and remove ,
#pop used to remove the particular index value
#remove used to remove the particular value

In [ ]:
#wap to remove  value 1 that present in entire list
l=[3,4,1,44,222,66,33,1,5,3,2,5,1]
l.remove(1)
print(l)

[3, 4, 44, 222, 66, 33, 1, 5, 3, 2, 5, 1]

In [ ]:
'''
tuple in python
tuple is immutable sequence of values.
a=(1,2,3)
we can't the change the value o tuple

'''

"\ntuple in python\ntuple is immutable sequence of values.\na=(1,2,3)\nwe can't the change the value o tuple\n\n"

In [ ]:
#wap to find len of the tuple
a=(12,4,5,2,5,22)
print(len(a))

6

In [ ]:
#wap to find 2nd index of the tuple
l=(12,4,66,22,5,12,665)
print(l[2])

66

In [ ]:
#wap to find the occurence of a number in tuple
l=(12,4,66,22,5,12,665)
l.count(12)

2

In [ ]:
#wap to remove an element from a tuple
''
'we cant use this remove because it is immatubale
''

SyntaxError: unterminated string literal (detected at line 3) (ipython-input-2317634865.py, line 3)

In [ ]:
#wap to ask the user to enter na,es,of their 3 Favourites movies & Store them in a lists
movies =[]
movie1=input("enter your 1st favourite movie::")
movies.append(movie1)
movie2=input("enter your 2nd favourite movie::")
movies.append(movie2)
movie3=input("enter your 3rd favourite movie::")
movies.append(movie3)
print(movies)

enter your 1st favourite movie::kgf
enter your 2nd favourite movie::jii
enter your 3rd favourite movie::ki
['kgf', 'jii', 'ki']

In [ ]:
''''
Dictionary in python:
a={
  ball:"football"
  b={
    bat:batman"
  }
}
"

In [ ]:
#wap to find all the keys that present inside a dictionary
a={
  "ball":"football",
  "bat":"batman"
}
print(a.keys())

dict_keys(['ball', 'bat'])

In [ ]:
#wap to find a all the values present inside a dictionary
a={
  "ball":"football",
  "bat":"batman"
}
print(a.values())

dict_values(['football', 'batman'])

In [ ]:
#wap to find the key value pair present inside the dictionary
a={
  "ball":"football",
  "bat":"batman"
}
print(a.items())

dict_items([('ball', 'football'), ('bat', 'batman')])

In [ ]:
#wap that return the key values according to values:
a={
  "ball":"football",
  "bat":"batman"
}
print(a.get("ball"))

football

In [ ]:
#wap to insert specific item in the dictionary
a={
    "balll":"football",
    "bat":"batman"
}
a["kit"]="basket"
print(a)

{'balll': 'football', 'bat': 'batman', 'kit': 'basket'}

In [ ]:
#wap to insert a new key value pair in dictionary
a={
    "balll":"football",
    "bat":"batman"
}
a["kit"]="basket"
print(a)

{'balll': 'football', 'bat': 'batman', 'kit': 'basket'}

In [ ]:
'''
set in python:
a={1,2,3}
'''

'\nset in python:\na={1,2,3}\n'

In [ ]:
#wap to add a new element in a set
a={1,2,3}
a.add(4)
print(a)

{1, 2, 3, 4}

In [ ]:
#wap to remove a element from a set
a={1,2,3}
a.remove(2)
print(a)

{1, 3}

In [ ]:
#wap to empty a entire set
a={1,2,3}
a.clear()
print(a)

set()

In [ ]:
#wap to randmonly remove an element from a set
a={1,2,3}
a.pop()
print(a)

{2, 3}

In [ ]:
#wap in which we have to create two different sets from from those two sets we have find the coomon elements
a={1,2,3}
b={3,4,5}
c=a.intersection(b)
print(c)

{3}

In [ ]:
#wap to create two different sets and then join two different sets into one
a={1,2,3}
b={3,4,5}
print(a.union(b))

{1, 2, 3, 4, 5}

In [ ]:
#wap to create two different sets and two different sets apart from the common element we have print the remaining element
a={1,2,3,4}
b={2,3,4,5,6}
c=a.symmetric_difference(b)
print(c)

{1, 5, 6}

In [ ]:
#figure out a way to store 9 &9.0 as separate values in the set
#(hint you can take help of built in data types. )
a={(9,float("9.0"))}
print(a)

{(9, 9.0)}

In [ ]:
#wap to store following word meanings in a oython dictionary:
#table:"a piece of furniture","list of facts and fingures"
#cate:"a small animal","a large animal"
a={"table":"a piece of furniture","list of facts and fingures":"table","cate":"a small animal","a large animal":"cate"}
print(a)

{'table': 'a piece of furniture', 'list of facts and fingures': 'table', 'cate': 'a small animal', 'a large animal': 'cate'}

In [ ]:
#you are given a list of subjects for students ,assume one classroom is required for 1subject.
#how many Classrooms are needed by all students
#"Python","java","c++","Python","javascript","java","python","java","c++","c"
a=["Python","java","c++","Python","javascript","java","Python","java","c++","c"]
b=set(a)
print(len(b))

5

In [ ]:
#figure out a way to store 9 &9.0 as separate values in the set
#(hint you can take help of built in data types. )
my_set = {9, 9.0}
print(my_set)
my_set_with_separate_values = {9, 9.0}
print(my_set_with_separate_values)

{9}
{9}

In [ ]:
#wap to print numbers from 1 to 100 using loops
for i in range(1,101):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [ ]:
#wap to print numbers from 1 to 100 using  while loops
i=1
while(i<=100):
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [ ]:
i=100
while(i>=1):
    print(i)
    i=i-1

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

In [ ]:
#wap in which we have create a list and print the conset of the list using loop
a=[1,2,3,4,5]
while

SyntaxError: invalid syntax (ipython-input-613870931.py, line 3)

In [ ]:
#wap to print number from 100 to 1 using for loop
for i in range(100,0,-1):
print(i)
#for i in range(start,stop,step)

IndentationError: expected an indented block after 'for' statement on line 2 (ipython-input-421068402.py, line 3)

In [ ]:
# Program to print multiplication table of a given number using for loop

num = int(input("Enter a number: "))
print(f"Multiplication table of {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

Enter a number: 67
Multiplication table of 67:
67 x 1 = 67
67 x 2 = 134
67 x 3 = 201
67 x 4 = 268
67 x 5 = 335
67 x 6 = 402
67 x 7 = 469
67 x 8 = 536
67 x 9 = 603
67 x 10 = 670

In [ ]:
#wap to print a equilateral triangle using for loop and while loop
a=6
for i  in range(a):
  for j in range (a-i-1):
    print("*",end="")
  for k in range(i+1):
    print(" * ",end="")
  print()

***** *
**** *  *
*** *  *  *
** *  *  *  *
* *  *  *  *  *
 *  *  *  *  *  *

In [ ]:
for i in range(6,0,-1):
  print("*"*i)

******
*****
****
***
**
*

In [ ]:
a=6
for i in range(a):
  for j in range (a-i-1):
    print(" ",end=" ")
  for k in range(2*i+1):
   print("*",end=" ")
  print()

          *
        * * *
      * * * * *
    * * * * * * *
  * * * * * * * * *
* * * * * * * * * * *

In [ ]:
#wap to print equilateral triangle using  while loop
#wap to print equilateral triangle using while loop
n=5
i=1
while i <= n:
  print(" "*(n-i) +"* "*(2*i-1))
  i+=1

    *
   * * *
  * * * * *
 * * * * * * *
* * * * * * * * *

In [ ]:
n= 5
i=1
while i <= n:
  print(" "*(n-i) +"* "*i)
  i+=1

    *
   * *
  * * *
 * * * *
* * * * *

In [ ]:
#wap to print  equilateral triangle ,hollo equilateral,diamond,butterfly,square,pyramid and hollo pyramid using both for and while loop

In [ ]:
from os.path import exists
from typing_extensions import Required
''''' an auto encoder is a type of neural network architecture that is used in deep learning for unsupervised learning and dimensionality reduction task .It is
primararily designed to learn efficient representation of data by encoding it into a latent space and the encoding it back to the original data space auto encoders
are widely used for various application such as data compression,denoising,feature learning and anamoley detection'''


Architecture of auto encoder two main parts
encoder and decoder


'''architecture of auto encoder
Encoder-encoder networks takes the input data in maps it to lower dimensional latent space which
 is often called as encoding or latent space .this encoding is typically compressed representationof the input data .
 the encoder can consists of 1 or more hidden layers and uses activation functions


Decoder-  decoder network takes the encoded represetation and attempt to reconstruct the orginal input
data from it .Like the encoder the decoder can also have one or more hidden layer and activation layer .


 The main objective of the auto encoder is to minize the reconstruction which measures how well the decoder can reconstruct
the input data from the encoded representation. common less function used for this purpose includes MSE(mean Squared error )
or binary cross entropy depending on the type of the data (continous or binary and the specific tasks



Training -auto encoder are trained in an unsupervised manner which means they donot require labbeled data. the training
process involves feeding input data into the encoder and encoding  it  to a lower dimensional representation and then decoded
it the original data the differnece the input and the reconstructed the output is to compute the loss
which is minized during the traning using the optimization technique  like gradiant decent)'''


Varitions in aut encoder
There are several variations of autoencoder each designed for specific task for data types.
some common types includes
1-denoising auto encoder-Trained to remove noise data by corrupting the input and reconstructing the clean data.
2-sparse Auto encoder- encourages the network to learn sparse representation whcih can be useful for feautre learning and dimensionality reduction.
3-variational auto encoder(VAE)-introduces proboabilistic elmensts in the latent space allowing for the  generation of new data samples and improve data compression.
4-convolutional Auto Encoder-specifically designed for image data using convolutional layer in the encoder and decoder.
5-recurrent Auto encoder-suitable for sequential data such as the time series by using recurrent layer in the architecture.


Now if we consider the numerical aspect of an autoencoder here is how it works
1-input data-Autoencoder takes numerical data as input this data could be anything from image(pixel values,audio) amplitude values
 over time text(both tokenization word embedding or any other form of numerical representation)
2-encoder-the encoder network recieves this numerical data and maps it to an lower dimensional numerical representation
for example in the case of image data the encoder might transform pixel values into a reduced set of numerical features
 that captures essential information.
3-latent space-compressed lower-dimensional and representation of high -dimensional input data.
4-decoder-the decoder takes the reduced numerical representation and attempts to reconstruct the original input data it does so by mapping the
reduced representation back to the original numerical format.
5-loss function-During traning the differnece between the input numerical data and the reconstructed data is measured using numerical loss
function the model adjusts its weights and biases from numerical optimization techniqueto minimize this loss


In Summary auto encoders are versatile tool in deep learning for learning compact representations of data and have numerious
representation in various domain working with both numerical and non numerical data


1-neural network-it generates same output
2-auto encoder-it generates different output based on the input,
3-variatinal auto encoder-it is same as AE it just provides better image.
4-Generative Model-it randomnly generate Images based on user Requirment


normal auto encoder                                                  |                 Variational autoencoder
why does this exist?                                                              why does this exists
what does this aptimize                                                           learns to generate new data
minimize Reconstruction loss                                                      what does this optimize
cannot generate new iamge                                                         Minimize reconsturction loss and latent loos


Generative model                                                      |               Variational autoencoder
how does this learns to genarative new data                                       consist of an encoder and decoder
consists of a generator and a discriminator networks
'''
'''

In [ ]:
rows = 9

for i in range(rows):
    for j in range(rows - i - 1):
        print(" ", end="")
    for k in range(2 * i + 1):
        print("*", end="")
    print()

        *
       ***
      *****
     *******
    *********
   ***********
  *************
 ***************
*****************

In [ ]:
rows = 5
i = 0

while i < rows:
    j = 0
    while j < rows - i - 1:
        print(" ", end="")
        j += 1
    k = 0
    while k < 2 * i + 1:
        print("*", end="")
        k += 1
    print()
    i += 1

    *
   ***
  *****
 *******
*********

In [ ]:
rows = 5

for i in range(rows):
    for j in range(rows - i - 1):
        print(" ", end="")


    if i == 0:
        print("*")
    elif i == rows - 1:
        for k in range(2 * i + 1):
            print("*", end="")
        print()
    else:
        print("*", end="")
        for k in range(2 * i - 1):
            print(" ", end="")
        print("*")

    *
   * *
  *   *
 *     *
*********

In [ ]:
rows = 5
i = 0

while i < rows:

    j = 0
    while j < rows - i - 1:
        print(" ", end="")
        j += 1


    if i == 0:
        print("*")
    elif i == rows - 1:
        k = 0
        while k < 2 * i + 1:
            print("*", end="")
            k += 1
        print()
    else:
        print("*", end="")
        k = 0
        while k < 2 * i - 1:
            print(" ", end="")
            k += 1
        print("*")
    i += 1

    *
   * *
  *   *
 *     *
*********

In [ ]:
rows = 5


for i in range(rows):

    for j in range(rows - i - 1):
        print(" ", end="")

    for k in range(2 * i + 1):
        print("*", end="")
    print()


for i in range(rows - 2, -1, -1):

    for j in range(rows - i - 1):
        print(" ", end="")

    for k in range(2 * i + 1):
        print("*", end="")
    print()

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *

In [ ]:
rows = 5


i = 0
while i < rows:

    j = 0
    while j < rows - i - 1:
        print(" ", end="")
        j += 1
    k = 0
    while k < 2 * i + 1:
        print("*", end="")
        k += 1
    print()
    i += 1


i = rows - 2
while i >= 0:

    j = 0
    while j < rows - i - 1:
        print(" ", end="")
        j += 1

    k = 0
    while k < 2 * i + 1:
        print("*", end="")
        k += 1
    print()
    i -= 1

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *

In [ ]:
rows = 5


for i in range(1, rows + 1):
    print("*" * i, end="")
    print(" " * (2 * (rows - i)), end="")
    print("*" * i)


for i in range(rows, 0, -1):
    print("*" * i, end="")
    print(" " * (2 * (rows - i)), end="")
    print("*" * i)

*        *
**      **
***    ***
****  ****
**********
**********
****  ****
***    ***
**      **
*        *

In [ ]:
rows = 5


i = 1
while i <= rows:
    print("*" * i, end="")
    print(" " * (2 * (rows - i)), end="")
    print("*" * i)
    i += 1


i = rows
while i >= 1:
    print("*" * i, end="")
    print(" " * (2 * (rows - i)), end="")
    print("*" * i)
    i -= 1

*        *
**      **
***    ***
****  ****
**********
**********
****  ****
***    ***
**      **
*        *

In [ ]:
size = 5

i = 0
while i < size:
    j = 0
    while j < size:
        print("*", end=" ")
        j += 1
    print()
    i += 1

* * * * *
* * * * *
* * * * *
* * * * *
* * * * *

In [ ]:
rows = 5

i = 0
while i < rows:

    j = 0
    while j < rows - i - 1:
        print(" ", end="")
        j += 1


    if i == 0:
        print("*")
    elif i == rows - 1:
        k = 0
        while k < 2 * i + 1:
            print("*", end="")
            k += 1
        print()
    else:
        print("*", end="")
        k = 0
        while k < 2 * i - 1:
            print(" ", end="")
            k += 1
        print("*")

    i += 1

    *
   * *
  *   *
 *     *
*********

In [ ]:
rows = 5

for i in range(rows):

    for j in range(rows - i - 1):
        print(" ", end="")


    if i == 0:
        print("*")
    elif i == rows - 1:
        for k in range(2 * i + 1):
            print("*", end="")
        print()
    else:
        print("*", end="")
        for k in range(2 * i - 1):
            print(" ", end="")
        print("*")

    *
   * *
  *   *
 *     *
*********

In [ ]:
'''
Functions in Python:
def greet(name):
  g = "hello" + name
  return gr

  a = greet("MITM")
  print(a)


'''''

'\nFunctions in Python:\ndef greet(name):\n  g = "hello" + name\n  return gr\n\n  a = greet("MITM")\n  print(a)\n\n\n'

In [ ]:
#wap to greet a user with good day with a function
def greet(name):
  print(f"Good day,{name}!")
greet("Alice")

Good day,Alice!

In [ ]:
#wap to print a length of list in which list is a parameter.

my_list_to_check = [10, 20, 30, 40, 50]
length = list_length(my_list_to_check)
print(f"The length of the list is: {length}")

NameError: name 'list_length' is not defined

In [ ]:
#wap to print the elements of a list in single line in which list is a parameter

# Example usage:
my_list = [1, 2, 3, 4, 5]
print_list_single_line(my_list)

NameError: name 'print_list_single_line' is not defined

In [ ]:
#wap to print factorial of n where n is the parameter.
number = 5
result = factorial(number)
print(f"The factorial of {number} is: {result}")

NameError: name 'factorial' is not defined

In [ ]:
#wap to convert usa dollars into indian rupees
def usd(n):
  c=90*n
  return c
a=usd(4)
print(a)

360

In [ ]:
#waf to print pallendrome of a list
def is_palindrome_list(lst):
  return lst == lst[::-1]


list1 = [1, 2, 3, 2, 1]
print(f"Is {list1} a palindrome? {is_palindrome_list(list1)}")

Is [1, 2, 3, 2, 1] a palindrome? True

In [ ]:
def is_palindrome_list(lst):
  return lst == lst[::-1]


list1 = [1, 2, 3, 2, 1]
print(f"Is {list1} a palindrome? {is_palindrome_list(list1)}")

Is [1, 2, 3, 2, 1] a palindrome? True

In [ ]:
#waf to calculate a square root of number that is given by a user

def square_root(n):
  return n**0.5
n=int(input("enter the number:"))
a=int(square_root(n))
print(a)

enter the number:8
2

In [ ]:

#waf to check if the number enter the by user even or odd
def even_odd(n):
  if n%2==0:
    print("even")
  else:
    print("odd")
n=int(input("enter the number"))
even_odd(n)

enter the number6
even

In [ ]:

##waf to calculate area of cylinder
def area_cylinder(r,h):
  area=2*3.14*r*(r+h)
  return area
r=int(input("enter the radius"))
h=int(input("enter the height"))
a=area_cylinder(r,h)
print(a)

enter the radius6
enter the height67
2750.64

In [ ]:
##waf to calculate sum and product of the number present inside the list
def sum_product(l):
  sum=0
  product=1
  for i in l:
    sum+=i
    product*=i
  return sum,product #this line should be in the def sum_product function
l=[1,2,3,4,5]
a=sum_product(l)
print(a)

(15, 120)

In [ ]:
'''
Recursion
''''''

def factorial(n):
  if n==0:
    return 1
  else:
    return n*factorial(n-1)

In [ ]:
#wap to calculate the factorial of a number.
def factorial(n):
  if n==0:
    return 1
  else:
    return n*factorial(n-1)
print(factorial(5))

120

In [ ]:
#wap a funtion to convert usd into inr
def usd_to_inr(usd_amount):
    if usd_amount < 0:
        return "Error: USD amount cannot be negative."
    else:
        conversion_rate = 90.33
        inr_amount = usd_amount * conversion_rate
        return inr_amount
usd = float(input("Enter amount in USD: "))
inr = usd_to_inr(usd)
if isinstance(inr, str):
    print(inr)
else:
    print(f"{usd} USD is equal to {inr:.2f} INR")

Enter amount in USD: 8

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

In [ ]:
''''
numpy is numerical opertaions (complex ) and store less space compared to other
''''

In [ ]:
'''
import is used import any function which is present the ptyhon library
variables store the data,value
identifier is used identify something
alias is different name of variables

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [ ]:
arr1=np.array([[1,2,3],[4,5,6,]])
print(arr1.ndim)

2

In [ ]:
#wap to find element present on the second index.
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])

3

In [ ]:
#wap to create an array of one thousand dimension.
import numpy as np
arr2=np.zeros([1]*64)
print(arr2.ndim)
print(arr2.shape)

64
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [ ]:
#wap to create an array of even number from 2-20 then calculate mean of an array
import numpy as np
arr=np.arange(2,22,2)
print(arr)
print(arr.mean())

[ 2  4  6  8 10 12 14 16 18 20]
11.0

In [ ]:
#wap to create two dimensional array consisting rows and columns multiply every element by 5 and then print the second columns

In [ ]:
#Wap to print elements presents on first and second index of the first row
import numpy as np
arr21=np.array([[1,2,3],[2,4,7]])
print(arr21[0,0:2])

[1 2]

In [ ]:
#wap print first to third index
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Elemenets from first index to third index:",arr[1:4])

Elemenets from first index to third index: [2 3 4]

In [ ]:
#wap print last 2.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Elemenets of last two",arr[-2:])

Elemenets of last two [ 9 10]

In [ ]:
#Wap print first 3
rr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Elemenets from first three :",arr[:3])

Elemenets from first three : [1 2 3]

In [ ]:
'''
pandas
in numpy array is create and in pandas it is used as series of data we not need to use print in pandas

'''

In [ ]:
import pandas as pd
s=pd.Series([1,3,4,2,5,6,7,8])
s

0    1
1    3
2    4
3    2
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
s.name="calories" #changing name from none to calories
s

0    1
1    3
2    4
3    2
4    5
5    6
6    7
7    8
Name: calories, dtype: int64

In [ ]:
#wap to create a series of object and print the elements present on 2nd,4th,and 6th index

In [ ]:
#wap to create series of elements to print from 2nd index to 6th index

In [ ]:
import pandas as pd
index=["apple","bannana","grapes","orange","strawbery"]
s=pd.Series([1,3,4,2,5])

In [ ]:
#wap to print the labelled based indexing that goes up to the 0th index to the 4th index.
s.index=index
s
s.loc['apple':'strawbery']

apple        1
bannana      3
grapes       4
orange       2
strawbery    5
dtype: int64

In [ ]:
import pandas as pd
fruit_protein={
    "Avocado":2.0,
    "Guava":2.6,
    "Blackburries":2.0,
    "Orages":0.9,
    "Banana":1.1,
    "Apples":0.3,
    "Kiwi":1.1,
    "Pomegrante":1.7,
    "Mango":0.8,
    "cherries":1.0
}

In [ ]:
#series to naming
s2=pd.Series(fruit_protein,name="Protein")
s2

Avocado         2.0
Guava           2.6
Blackburries    2.0
Orages          0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegrante      1.7
Mango           0.8
cherries        1.0
Name: Protein, dtype: float64

In [ ]:
#conditional
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackburries    2.0
Banana          1.1
Kiwi            1.1
Pomegrante      1.7
Name: Protein, dtype: float64

In [ ]:
#logical opertor
s2[(s2>0.5) | (s2<=2) ]

Avocado         2.0
Guava           2.6
Blackburries    2.0
Orages          0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegrante      1.7
Mango           0.8
cherries        1.0
Name: Protein, dtype: float64

In [ ]:
import numpy as np

In [ ]:
import numpy as np
ser=pd.Series(['a',np.nan,1,np.nan,2])
s.notnull().sum()

np.int64(5)

In [ ]:
#data frame
data={
    "Name":["Alice","Bob","Charlie","David","Eve","ALice"],
    "Age":[25,30,35,np.nan,29,25],
   "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000,60000,70000,62000,np.nan,50000]
}

In [ ]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    ALice  25.0         HR  50000.0

In [ ]:
df.head(2)

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [ ]:
#loc and iloc
df.iloc[1:3,:2]#rows

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [ ]:
df.loc[1:2,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [ ]:
df[["Age","Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [ ]:
df.drop("Age",axis=1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    ALice         HR  50000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info

<bound method DataFrame.info of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    ALice  25.0         HR  50000.0>

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [ ]:
#Broad casting
df["Salary"]=df["Salary"]+5000
df

      Name   Age Department   Salary
0    Alice  25.0         HR  55000.0
1      Bob  30.0         IT  65000.0
2  Charlie  35.0    Finance  75000.0
3    David   NaN         IT  67000.0
4      Eve  29.0         HR      NaN
5    ALice  25.0         HR  55000.0

In [ ]:
df.rename(columns={"Department":"dept"},inplace=True)
df

      Name   Age     dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    ALice  25.0       HR  55000.0

In [ ]:
df["dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
df["dept"].value_counts()

dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["promoted salary"]=df["Salary"]*10
df

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    ALice  25.0       HR  55000.0         550000.0

In [ ]:
df.isnull().sum()

Name               0
Age                1
dept               0
Salary             1
promoted salary    1
dtype: int64

In [ ]:
df.dropna(how="any")#any row that has any null value

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    ALice  25.0       HR  55000.0         550000.0

In [ ]:
df.dropna(how="all")#all row that has all null value

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    ALice  25.0       HR  55000.0         550000.0

In [ ]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method="ffill")

/tmp/ipython-input-310954073.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method="bfill")

/tmp/ipython-input-3345892411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:




''''
GAN
Generative Adversal network
''''

In [ ]:
For the discriminator to help distinguish the real data from the fake generated data.